name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ci ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Linux
    steps:
    ### Bare metal server installation. Flow:
      # 1. checkout the version
#      - uses: actions/checkout@v3
    ### docker only checkout
      # 1. checkout 
#      - uses: actions/checkout@v3
    ### docker checkout and re-build
      - name: cd into folder
        run: |
          cd /stack-on-docker/ci/PT-API
          sudo whoami
          sudo git pull
          pwd

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "Short SHA is ${{ env.SHORT_SHA }}"
#          docker compose down || echo "stack is already down"
#          docker compose up -d

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .ci/Dockerfile
          push: false
          tags: test:${{ steps.vars.outputs.sha_short }}


#       - uses: isbang/compose-action@v1.5.1
#         with:
#           compose-file: "/stack-on-docker/ci/PT-API/docker-compose.yaml"
#           up-flags: "/stack-on-docker/ci/PT-API/docker-compose.yaml"
#  #         echo Add other actions to build,
 #         echo test, and deploy your project.